name: secure_random
description: A secure random generator to generate cryptographically secure random string.
version: 1.0.1
author: "Ming Chen <ming_c@hotmail.com>"
homepage: https://github.com/mingchen/secure_random

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:


dev_dependencies:
  test: ^1.3.0
